create:
  fields:
    name:
      required: true
      selector:
        text:
    trigger_template:
      required: true
      selector:
        template:
    repeat:
      required: true
      selector:
        number:
          min: 1
          max: 9999
          step: 1
          unit_of_measurement: minutes
    skip_first:
      default: false
      selector:
        boolean:
    notifiers:
      required: true
      selector:
        text:
          multiple: true
    message:
      selector:
        template:
    done_message:
      selector:
        template:
    title:
      selector:
        template:
    data:
      selector:
        object:

update:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: switch
          integration: ha_alerts
    trigger_template:
      selector:
        template:
    repeat:
      selector:
        number:
          min: 1
          max: 9999
          step: 1
          unit_of_measurement: minutes
    skip_first:
      selector:
        boolean:
    notifiers:
      selector:
        text:
          multiple: true
    message:
      selector:
        template:
    done_message:
      selector:
        template:
    title:
      selector:
        template:
    data:
      selector:
        object:

delete:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: switch
          integration: ha_alerts
